<a href="https://colab.research.google.com/github/LiliContreras/THC_Lilibeth/blob/main/EjercicioClase_24Oct_LilibethContreras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Arreglos 1D


In [1]:
import numpy as np

In [2]:
#Indices:     0 1 2 3 4 5 6
arr=np.array([1,2,3,4,5,6,7])

print(arr[1:5])

[2 3 4 5]


In [3]:
print(arr[1:])
print(arr[0:4])

[2 3 4 5 6 7]
[1 2 3 4]


índices con números negativos

In [5]:
#Lista:   1  2  3  4  5  6  7
#Indices:-7 -6 -5 -4 -3 -2 -1
print(arr[-3:-1])

[5 6]


arreglo[inicio:fin:paso]

In [6]:
print(arr[1:5:2])  #Va desde 1 hasta 5, con un paso de 2. Avanza de 2 en 2

[2 4]


In [8]:
print(arr[::1])

[1 2 3 4 5 6 7]


In [12]:
print(arr[0:])

[1 2 3 4 5 6 7]


In [13]:
print(arr[:0])

[]


Rebanar por renglones

In [14]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
'''
I  0 1 2 3 4
0  1 2 3 4 5
1  6 7 8 9 10
'''
print(arr[1,1:4])

[7 8 9]


Rebanar por columnas

In [18]:
print(arr[0:2,2]) #El úlñtimo vslor no lo toma en cuenta, va en renglón 0 y 1 en columna 2

[3 8]


In [20]:
print(arr[0:2,3])

[4 9]


In [22]:
print(arr[0,4])

5


In [23]:
print(arr[0:2,1:4]) #Renglones: 0 y 1 Columnas: 1,2 y 3

[[2 3 4]
 [7 8 9]]


In [24]:
print(arr[0:1,2:5])

[[3 4 5]]


Se pueden buscar sobre arreglos, hacer comparaciones etc.

In [26]:
arr=np.array([1,2,3,4,5,4,4])

x=np.where(arr==4)

print(x)

(array([3, 5, 6]),)


In [27]:
#Donde elementos del arreglo son divisibles entre 2:
arr=np.array([1,2,3,4,5,6,7,8])

x=np.where(arr%2 ==0 )

print(x)

(array([1, 3, 5, 7]),)


In [28]:
arr=np.array([6,7,8,9])

x=np.searchsorted(arr,7) #Busca donde está ese elemento (lista debe estar ordenada)

print(x)

1


In [30]:
#Comparaciones:
arr=np.array([41,42,43,44])

filter_arr=arr>42 #Revisa que valores dentro de arreglo son mayores a 42

newarr=arr[filter_arr] #Agarra elementos que cumplen condición, formando nuevo arreglo

print(filter_arr) #Imprime que elementos cumplen condición
print(newarr)

[False False  True  True]
[43 44]


#Ejercicios

In [37]:
x=np.array([1,2,3])
y=np.array([4,5,6])

#Suma:
suma=x+y
print('Resultado de suma es: ')
print(suma)

#Imprimir de otra forma:
print(f'La suma es {suma}')

#Resta:
resta=x-y
print('Resultado de resta es: ')
print(resta)

#Multiplicación:
mult=x*y
print('Resultado de multiplicación es: ')
print(mult)

#División:
div=x/y
print('Resultado de división es: ')
print(div)

Resultado de suma es: 
[5 7 9]
La suma es [5 7 9]
Resultado de resta es: 
[-3 -3 -3]
Resultado de multiplicación es: 
[ 4 10 18]
Resultado de división es: 
[0.25 0.4  0.5 ]


In [38]:
print(f'Número pi= {np.pi}')

Número pi= 3.141592653589793


In [39]:
angulos=np.array([0,np.pi/2,np.pi])
seno=np.sin(angulos)
print(f'Los senos {seno} de los ángulos {angulos}')

Los senos [0.0000000e+00 1.0000000e+00 1.2246468e-16] de los ángulos [0.         1.57079633 3.14159265]


In [40]:
coseno=np.cos(angulos)
print(f'Los angulos {coseno}')
print(f'de los ángulos {angulos}')

Los angulos [ 1.000000e+00  6.123234e-17 -1.000000e+00]
de los ángulos [0.         1.57079633 3.14159265]


Crear arreglos:

In [42]:
x=np.array(list(range(1,9)))
print(x)

[1 2 3 4 5 6 7 8]


Como crear matriz a partir de arreglo:

In [43]:
matriz=x.reshape(2,4)
matriz

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
matriz2=x.reshape(4,2)
matriz2

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

Arreglo a matriz:

In [45]:
x.reshape(-1,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [46]:
x.reshape(-1,1).shape

(8, 1)

In [52]:
x=np.linspace(0,1,9)
x

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [53]:
#Numeros aleatorios con numpy:
np.random.uniform(0,1,6)


array([0.51704964, 0.34794142, 0.62013558, 0.07020773, 0.40476758,
       0.48979341])

In [54]:
#Números aleatorios enteros:
np.random.randint(0,10,3)

array([1, 9, 1])

#Ejercicio
Crear arreglo del 1 al 10, pedir un número del 1 al 10 y luego adivinar el número:


In [59]:
arreglo=np.array(list(range(1,11)))
num=int(input('Ingresa un número: '))

magia=0
while magia != num:
  magia=np.random.randint(1,11,1)
  print(f'Tu número es: {magia}')
  if magia != num:
    print('No :(')
  else:
    print('Si uwu')

Ingresa un número: 2
Tu número es: [9]
No :(
Tu número es: [10]
No :(
Tu número es: [10]
No :(
Tu número es: [6]
No :(
Tu número es: [1]
No :(
Tu número es: [6]
No :(
Tu número es: [2]
Si uwu
