<a href="https://colab.research.google.com/github/LiliContreras/THC_Lilibeth/blob/main/EjercicioClase_19Oct_LilibethContreras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy

**Importante**

Biblioteca para hacer cálculos numéricos


In [1]:
#Importar numpy:
import numpy as np #np: alias de numpy

In [4]:
arr= np.array([1,2,3,4,5]) #Entre el paréntesis meto la lista

print(arr)

print(type(arr)) #Tipo: es un arreglo de numpy

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
arr1= np.array((1,2,3,4,5)) #Entre el paréntesis meto una tupla

print(arr1)

print(type(arr1)) #Tipo: es un arreglo de numpy

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
matriz=np.array([[1,2,3],[4,5,6]]) #Arreglo bidimensional
print(matriz)

[[1 2 3]
 [4 5 6]]


##Arreglos 3-D

In [8]:
arr3=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


Shape= cantidad de columnas y renglones de matriz
ndim= dimensiones



In [10]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim,a.shape)
print(b.ndim,b.shape)
print(c.ndim,c.shape)
print(d.ndim,d.shape)

0 ()
1 (5,)
2 (2, 3)
3 (2, 2, 3)


##Acceder a elementos de arreglos

In [11]:
print(b[0])

1


In [13]:
#c:
# 0 1 2 <- Columnas
# 1 2 3  Fila 0
# 4 5 6  Fila 1
print(c[0,1]) #Imprime fila 0 y columna 1

2


In [14]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
#arr:
# Dimensión 0:       Dimensión 1
# 0 1 2 <- Columnas ->0  1  2
# 1 2 3  Fila 0       7  8  9  Fila 0
# 4 5 6  Fila 1       10 11 12 Fila 1


print(arr[0,1,2])

6


##Ejercicio:

In [36]:
#Listas:
#matrizL=[[1,2,3],[4,5,6],[7,8,9]]
matrizL=[[1,1,1],[1,1,1],[1,1,1]]
matriznp=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
#Suma de los elementos de la matriz:

#Con la lista normal:
Suma=0
for i in range(len(matrizL)):
  for j in range(len(matrizL)):
    Suma=Suma+matrizL[i][j]
    #print('%d + %d'%(Suma,matrizL[i][j]))
print('La suma de los elementos de la matriz es: %d'%Suma)

La suma de los elementos de la matriz es: 9


In [39]:
#Suma con matriz de numpy:
shp=matriznp.shape
suma=0
for i in range(shp[1]):
  for j in range(shp[1]):
    suma=suma+matriznp[i,j]
    #print('%d + %d'%(suma,matriznp[i,j]))
print('La suma de los elementos de la matriz es: %d'%suma)

La suma de los elementos de la matriz es: 45


##Producto escalar por renglones:

In [26]:
A=[[1,2],[3,4]]    #  1  2     5  6
B=[[5,6],[7,8]]    #  3  4     7  8
final=[]
for i in range(len(A)):
  suma=0
  for j in range(len(A)):
    C=A[i][j]*B[i][j]
    suma=suma+C
    #print(suma)
  final.append(suma)

print(final)

[17, 53]


##Producto escalar por columnas

In [27]:
final=[]
for j in range(len(A)):
  suma=0
  for i in range(len(A)):
    C=A[i][j]*B[i][j]
    suma=suma+C
    #print(suma)
  final.append(suma)

print(final)

[26, 44]


##Con arreglos Numpy:

In [34]:
#Producto por renglones

A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])


final=[]
shp=A.shape

for i in range(shp[0]):
  suma=0
  for j in range(shp[0]):
    C=A[i,j]*B[i,j]
    suma=suma+C
    #print(suma)
  final.append(suma)

print(final)


[17, 53]


In [35]:
#Producto por renglones

final=[]
shp=A.shape

for j in range(shp[0]):
  suma=0
  for i in range(shp[0]):
    C=A[i,j]*B[i,j]
    suma=suma+C
    #print(suma)
  final.append(suma)

print(final)

[26, 44]


In [41]:
#¿Cómo funciona "append" en arreglos de numpy?
prueba=np.array([1,2,3])
prueba1=np.array([4,5,6])
print(prueba)
print(prueba1)

fin=np.append(prueba,prueba1)

print(fin)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
